server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 40M;

    location = /docs/openapi {
        return 301 /docs/openapi/;
    }

    location /docs/openapi/ {
        alias /var/www/docs/openapi/;
        index index.html;

        types {
            text/html                             html;
            text/yaml                             yaml yml;
            application/javascript                js;
            text/css                              css;
        }
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
